# Generated by Django 5.0.8 on 2025-09-28 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity_app", "0007_add_nationality_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VulnerabilityAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "global_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Score global vulnérabilité (0-100)",
                    ),
                ),
                (
                    "vulnerability_level",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critique"),
                            ("HIGH", "Élevée"),
                            ("MODERATE", "Modérée"),
                            ("LOW", "Faible"),
                        ],
                        max_length=20,
                        verbose_name="Niveau vulnérabilité",
                    ),
                ),
                (
                    "dimension_scores",
                    models.JSONField(default=dict, verbose_name="Scores par dimension"),
                ),
                (
                    "priority_interventions",
                    models.JSONField(
                        default=list, verbose_name="Interventions prioritaires"
                    ),
                ),
                (
                    "social_programs_eligibility",
                    models.JSONField(
                        default=dict, verbose_name="Éligibilité programmes sociaux"
                    ),
                ),
                (
                    "geographic_priority_zone",
                    models.CharField(
                        max_length=30, verbose_name="Zone priorité géographique"
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Score confiance évaluation",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date évaluation"
                    ),
                ),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Évaluateur",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerability_assessments",
                        to="identity_app.personidentity",
                        verbose_name="Personne évaluée",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation vulnérabilité",
                "verbose_name_plural": "Évaluations vulnérabilité",
                "db_table": "services_vulnerability_assessments",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="SocialProgramEligibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "program_code",
                    models.CharField(
                        choices=[
                            ("TRANSFERTS_MONETAIRES", "Transferts Monétaires"),
                            ("NUTRITION_MATERNELLE", "Nutrition Maternelle"),
                            ("DEVELOPPEMENT_RURAL", "Développement Rural"),
                            ("FORMATION_PROFESSIONNELLE", "Formation Professionnelle"),
                            ("AIDE_URGENCE", "Aide d'Urgence"),
                            ("SANTE_GRATUITE", "Soins Santé Gratuits"),
                            ("BOURSES_EDUCATION", "Bourses Éducation"),
                            ("APPUI_HANDICAP", "Appui Handicap"),
                        ],
                        max_length=50,
                        verbose_name="Code programme",
                    ),
                ),
                (
                    "eligibility_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Score éligibilité (0-100)",
                    ),
                ),
                (
                    "recommendation_level",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immédiate"),
                            ("HIGH", "Prioritaire"),
                            ("MEDIUM", "Modérée"),
                            ("LOW", "Faible"),
                        ],
                        max_length=20,
                        verbose_name="Niveau recommandation",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_eligibilities",
                        to="identity_app.personidentity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "db_table": "services_program_eligibility",
                "unique_together": {("person", "program_code")},
            },
        ),
    ]
