# Generated by Django 5.0.8 on 2025-10-10 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs_app", "0001_initial"),
        ("services_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programbudgetchange",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_changes",
                to="programs_app.socialprogram",
                verbose_name="Programme",
            ),
        ),
        migrations.AddField(
            model_name="vulnerabilityassessment",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vulnerability_assessments",
                to="programs_app.socialprogram",
                verbose_name="Programme",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="SocialProgram",
        ),
    ]
