# Generated by Django 5.0.8 on 2025-10-09 17:07

import apps.identity_app.models.person
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "household_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID Ménage"
                    ),
                ),
                (
                    "household_type",
                    models.CharField(
                        choices=[
                            ("NUCLEAR", "Nucléaire"),
                            ("EXTENDED", "Étendu"),
                            ("SINGLE_PARENT", "Monoparental"),
                            ("SINGLE_PERSON", "Personne Seule"),
                            ("COLLECTIVE", "Collectif"),
                        ],
                        default="NUCLEAR",
                        max_length=20,
                        verbose_name="Type de Ménage",
                    ),
                ),
                (
                    "household_size",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Taille du Ménage",
                    ),
                ),
                (
                    "members_under_15",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Membres < 15 ans"
                    ),
                ),
                (
                    "members_15_64",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Membres 15-64 ans"
                    ),
                ),
                (
                    "members_over_64",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Membres > 64 ans"
                    ),
                ),
                (
                    "housing_type",
                    models.CharField(
                        choices=[
                            ("OWNED", "Propriétaire"),
                            ("RENTED", "Locataire"),
                            ("FREE", "Logé Gratuitement"),
                            ("PRECARIOUS", "Logement Précaire"),
                            ("NO_HOUSING", "Sans Logement"),
                        ],
                        max_length=20,
                        verbose_name="Type de Logement",
                    ),
                ),
                (
                    "number_of_rooms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de Pièces"
                    ),
                ),
                (
                    "water_access",
                    models.CharField(
                        choices=[
                            ("PIPED", "Eau Courante"),
                            ("WELL", "Puits"),
                            ("BOREHOLE", "Forage"),
                            ("SPRING", "Source"),
                            ("VENDOR", "Vendeur d'Eau"),
                            ("NONE", "Pas d'Accès"),
                        ],
                        max_length=20,
                        verbose_name="Accès à l'Eau",
                    ),
                ),
                (
                    "electricity_access",
                    models.CharField(
                        choices=[
                            ("GRID", "Réseau National"),
                            ("GENERATOR", "Générateur"),
                            ("SOLAR", "Solaire"),
                            ("BATTERY", "Batterie"),
                            ("NONE", "Pas d'Électricité"),
                        ],
                        max_length=20,
                        verbose_name="Accès à l'Électricité",
                    ),
                ),
                (
                    "has_toilet",
                    models.BooleanField(default=False, verbose_name="Accès Toilettes"),
                ),
                (
                    "total_monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Revenus Totaux Mensuels (FCFA)",
                    ),
                ),
                (
                    "has_bank_account",
                    models.BooleanField(default=False, verbose_name="Compte Bancaire"),
                ),
                (
                    "assets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des biens du ménage",
                        verbose_name="Biens",
                    ),
                ),
                (
                    "has_agricultural_land",
                    models.BooleanField(default=False, verbose_name="Terre Agricole"),
                ),
                (
                    "agricultural_land_size",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Superficie Agricole (hectares)",
                    ),
                ),
                (
                    "livestock",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Bétail/Élevage"
                    ),
                ),
                (
                    "has_disabled_members",
                    models.BooleanField(
                        default=False, verbose_name="Membres en Situation de Handicap"
                    ),
                ),
                (
                    "has_elderly_members",
                    models.BooleanField(default=False, verbose_name="Personnes Âgées"),
                ),
                (
                    "has_pregnant_women",
                    models.BooleanField(default=False, verbose_name="Femmes Enceintes"),
                ),
                (
                    "has_children_under_5",
                    models.BooleanField(default=False, verbose_name="Enfants < 5 ans"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Province"
                    ),
                ),
                (
                    "last_visit_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière Visite"
                    ),
                ),
                (
                    "vulnerability_score",
                    models.FloatField(
                        default=0.0, verbose_name="Score de Vulnérabilité"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ménage",
                "verbose_name_plural": "Ménages",
                "db_table": "rsu_households",
                "ordering": ["household_id"],
            },
        ),
        migrations.CreateModel(
            name="PersonIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "rsu_id",
                    models.CharField(
                        help_text="Identifiant unique RSU Gabon",
                        max_length=50,
                        unique=True,
                        verbose_name="RSU ID",
                    ),
                ),
                (
                    "nip",
                    models.CharField(
                        blank=True,
                        help_text="Numéro d'Identification Personnel (RBPP)",
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="NIP",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="Carte Nationale d'Identité ou Passeport",
                        max_length=50,
                        null=True,
                        verbose_name="CNI/Passeport",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Prénom(s)"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nom de famille"),
                ),
                (
                    "maiden_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nom de jeune fille",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Date de naissance")),
                (
                    "birth_place",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Lieu de naissance",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Masculin"),
                            ("F", "Féminin"),
                            ("O", "Autre/Non spécifié"),
                        ],
                        max_length=1,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Célibataire"),
                            ("MARRIED", "Marié(e)"),
                            ("DIVORCED", "Divorcé(e)"),
                            ("WIDOW", "Veuf/Veuve"),
                            ("COHABITING", "Concubinage"),
                            ("SEPARATED", "Séparé(e)"),
                        ],
                        default="SINGLE",
                        max_length=15,
                        verbose_name="Statut matrimonial",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("GABONAISE", "Gabonaise"),
                            ("AUTRE_CEMAC", "Autre CEMAC"),
                            ("AUTRE_AFRIQUE", "Autre Afrique"),
                            ("AUTRE", "Autre"),
                        ],
                        default="GABONAISE",
                        max_length=50,
                        verbose_name="Nationalité",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Format: +241XXXXXXXX ou 0XXXXXXXX",
                        max_length=20,
                        null=True,
                        validators=[
                            apps.identity_app.models.person.validate_gabonese_phone
                        ],
                        verbose_name="Numéro de Téléphone",
                    ),
                ),
                (
                    "phone_number_alt",
                    models.CharField(
                        blank=True,
                        help_text="Numéro secondaire (optionnel)",
                        max_length=20,
                        null=True,
                        validators=[
                            apps.identity_app.models.person.validate_gabonese_phone
                        ],
                        verbose_name="Téléphone Alternatif",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "Aucune"),
                            ("INCOMPLETE_PRIMARY", "Primaire Incomplet"),
                            ("PRIMARY", "Primaire"),
                            ("SECONDARY", "Secondaire"),
                            ("HIGH_SCHOOL", "Baccalauréat"),
                            ("TECHNICAL", "Formation Technique"),
                            ("UNIVERSITY", "Universitaire"),
                            ("POSTGRADUATE", "Post-universitaire"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Niveau d'éducation",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Profession"
                    ),
                ),
                (
                    "employer",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'entreprise/organisation employeur",
                        max_length=200,
                        null=True,
                        verbose_name="Employeur",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMPLOYED_FORMAL", "Employé Formel (CDI/CDD)"),
                            ("EMPLOYED_INFORMAL", "Employé Informel"),
                            ("SELF_EMPLOYED", "Travailleur Indépendant"),
                            ("UNEMPLOYED", "Sans Emploi"),
                            ("STUDENT", "Étudiant"),
                            ("RETIRED", "Retraité"),
                            ("HOMEMAKER", "Au Foyer"),
                            ("UNABLE_TO_WORK", "Inapte au Travail"),
                        ],
                        help_text="Situation professionnelle actuelle",
                        max_length=20,
                        null=True,
                        verbose_name="Statut d'Emploi",
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Revenus mensuels (FCFA)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude GPS",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude GPS",
                    ),
                ),
                (
                    "gps_accuracy",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Précision GPS (mètres)"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ESTUAIRE", "Estuaire"),
                            ("HAUT_OGOOUE", "Haut-Ogooué"),
                            ("MOYEN_OGOOUE", "Moyen-Ogooué"),
                            ("NGOUNIE", "Ngounié"),
                            ("NYANGA", "Nyanga"),
                            ("OGOOUE_IVINDO", "Ogooué-Ivindo"),
                            ("OGOOUE_LOLO", "Ogooué-Lolo"),
                            ("OGOOUE_MARITIME", "Ogooué-Maritime"),
                            ("WOLEU_NTEM", "Woleu-Ntem"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Province",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Département",
                    ),
                ),
                ("commune", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="District/Quartier",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse complète"
                    ),
                ),
                (
                    "has_disability",
                    models.BooleanField(
                        default=False, verbose_name="Situation de handicap"
                    ),
                ),
                (
                    "disability_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Détails handicap"
                    ),
                ),
                (
                    "is_household_head",
                    models.BooleanField(default=False, verbose_name="Chef de ménage"),
                ),
                (
                    "vulnerability_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculé automatiquement par le service de vulnérabilité",
                        max_digits=5,
                        null=True,
                        verbose_name="Score de vulnérabilité (0-100)",
                    ),
                ),
                (
                    "vulnerability_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CRITICAL", "Critique"),
                            ("HIGH", "Élevée"),
                            ("MODERATE", "Modérée"),
                            ("LOW", "Faible"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Niveau de vulnérabilité",
                    ),
                ),
                (
                    "last_vulnerability_assessment",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Dernière évaluation vulnérabilité",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En Attente"),
                            ("VERIFIED", "Vérifié"),
                            ("REJECTED", "Rejeté"),
                            ("REQUIRES_REVIEW", "Nécessite Révision"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut vérification",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date vérification"
                    ),
                ),
                (
                    "data_completeness_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Score complétude (%)",
                    ),
                ),
                (
                    "rbpp_synchronized",
                    models.BooleanField(default=False, verbose_name="Synchronisé RBPP"),
                ),
                (
                    "rbpp_sync_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière sync RBPP"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_persons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vérifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identité Personne",
                "verbose_name_plural": "Identités Personnes",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "relationship_to_head",
                    models.CharField(
                        choices=[
                            ("HEAD", "Chef de Ménage"),
                            ("SPOUSE", "Époux/Épouse"),
                            ("CHILD", "Enfant"),
                            ("PARENT", "Parent"),
                            ("SIBLING", "Frère/Sœur"),
                            ("GRANDPARENT", "Grand-Parent"),
                            ("GRANDCHILD", "Petit-Enfant"),
                            ("UNCLE_AUNT", "Oncle/Tante"),
                            ("COUSIN", "Cousin/Cousine"),
                            ("NEPHEW_NIECE", "Neveu/Nièce"),
                            ("IN_LAW", "Beau-parent/Belle-famille"),
                            ("ADOPTED", "Adopté(e)"),
                            ("FOSTER", "Enfant Accueilli"),
                            ("DOMESTIC_WORKER", "Employé(e) Domestique"),
                            ("LODGER", "Locataire/Pensionnaire"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Relation au Chef de Ménage",
                    ),
                ),
                (
                    "joined_household_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date d'Entrée dans le Ménage",
                    ),
                ),
                (
                    "left_household_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de Sortie du Ménage"
                    ),
                ),
                (
                    "is_current_member",
                    models.BooleanField(default=True, verbose_name="Membre Actuel"),
                ),
                (
                    "contributes_to_income",
                    models.BooleanField(
                        default=False, verbose_name="Contribue aux Revenus"
                    ),
                ),
                (
                    "monthly_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Contribution Mensuelle (FCFA)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="identity_app.household",
                        verbose_name="Ménage",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_memberships",
                        to="identity_app.personidentity",
                        verbose_name="Personne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre de Ménage",
                "verbose_name_plural": "Membres de Ménage",
                "db_table": "rsu_household_members",
                "ordering": ["household", "relationship_to_head"],
            },
        ),
        migrations.AddField(
            model_name="household",
            name="head_of_household",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="headed_household",
                to="identity_app.personidentity",
                verbose_name="Chef de Ménage",
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="head_person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="headed_household_alt",
                to="identity_app.personidentity",
                verbose_name="Chef de Ménage (Référence alternative)",
            ),
        ),
        migrations.CreateModel(
            name="RBPPSync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("VALIDATION", "Validation NIP"),
                            ("DATA_FETCH", "Récupération Données"),
                            ("UPDATE", "Mise à Jour"),
                            ("VERIFICATION", "Vérification Biométrique"),
                            ("BULK_SYNC", "Synchronisation Massive"),
                        ],
                        max_length=20,
                        verbose_name="Type de Sync",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En Attente"),
                            ("IN_PROGRESS", "En Cours"),
                            ("SUCCESS", "Réussie"),
                            ("FAILED", "Échouée"),
                            ("TIMEOUT", "Délai Dépassé"),
                            ("PARTIAL", "Partielle"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "rbpp_request_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID Requête RBPP",
                    ),
                ),
                (
                    "nip_requested",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="NIP Demandé"
                    ),
                ),
                (
                    "nip_returned",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        verbose_name="NIP Retourné",
                    ),
                ),
                (
                    "rbpp_response_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données Réponse RBPP"
                    ),
                ),
                (
                    "biometric_match_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Score Correspondance Biométrique",
                    ),
                ),
                (
                    "data_discrepancies",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Incohérences Données"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Code Erreur"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Message Erreur"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Démarré à"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé à"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée (secondes)"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de Tentatives"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Max Tentatives"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prochaine Tentative"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rbpp_syncs",
                        to="identity_app.personidentity",
                        verbose_name="Personne",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synchronisation RBPP",
                "verbose_name_plural": "Synchronisations RBPP",
                "db_table": "rsu_rbpp_syncs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeographicData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "location_name",
                    models.CharField(max_length=200, verbose_name="Nom localité"),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ESTUAIRE", "Estuaire"),
                            ("HAUT_OGOOUE", "Haut-Ogooué"),
                            ("MOYEN_OGOOUE", "Moyen-Ogooué"),
                            ("NGOUNIE", "Ngounié"),
                            ("NYANGA", "Nyanga"),
                            ("OGOOUE_IVINDO", "Ogooué-Ivindo"),
                            ("OGOOUE_LOLO", "Ogooué-Lolo"),
                            ("OGOOUE_MARITIME", "Ogooué-Maritime"),
                            ("WOLEU_NTEM", "Woleu-Ntem"),
                        ],
                        max_length=50,
                        verbose_name="Province",
                    ),
                ),
                (
                    "commune",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Commune"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Département",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="District/Arrondissement",
                    ),
                ),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("URBAN_CENTER", "Centre Urbain"),
                            ("URBAN_PERIPHERY", "Périphérie Urbaine"),
                            ("RURAL_ACCESSIBLE", "Rural Accessible"),
                            ("RURAL_REMOTE", "Rural Isolé"),
                            ("COASTAL", "Zone Côtière"),
                            ("FOREST", "Zone Forestière"),
                            ("MINING", "Zone Minière"),
                            ("BORDER", "Zone Frontalière"),
                        ],
                        default="RURAL_ACCESSIBLE",
                        max_length=30,
                        verbose_name="Type de zone",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-4.0),
                            django.core.validators.MaxValueValidator(2.3),
                        ],
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(8.5),
                            django.core.validators.MaxValueValidator(14.5),
                        ],
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "distance_to_hospital",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Distance au centre de santé le plus proche",
                        null=True,
                        verbose_name="Distance hôpital (km)",
                    ),
                ),
                (
                    "distance_to_school",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Distance à l'école primaire la plus proche",
                        null=True,
                        verbose_name="Distance école (km)",
                    ),
                ),
                (
                    "distance_to_market",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Distance marché (km)"
                    ),
                ),
                (
                    "distance_to_road",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Distance route praticable (km)",
                    ),
                ),
                (
                    "has_electricity",
                    models.BooleanField(
                        default=False, verbose_name="Accès électricité"
                    ),
                ),
                (
                    "has_water",
                    models.BooleanField(
                        default=False, verbose_name="Accès eau potable"
                    ),
                ),
                (
                    "has_road_access",
                    models.BooleanField(
                        default=False, verbose_name="Accès routier praticable"
                    ),
                ),
                (
                    "has_mobile_coverage",
                    models.BooleanField(
                        default=False, verbose_name="Couverture mobile"
                    ),
                ),
                (
                    "has_internet",
                    models.BooleanField(default=False, verbose_name="Accès internet"),
                ),
                (
                    "estimated_population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Population estimée"
                    ),
                ),
                (
                    "population_density",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VERY_LOW", "Très Faible"),
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Élevée"),
                            ("VERY_HIGH", "Très Élevée"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Densité population",
                    ),
                ),
                (
                    "accessibility_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Score accessibilité (0-100)",
                    ),
                ),
                (
                    "vulnerability_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Score vulnérabilité (0-100)",
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Élevée"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Niveau priorité",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Données Géographiques",
                "verbose_name_plural": "Données Géographiques",
                "db_table": "rsu_geographic_data",
                "ordering": ["province", "location_name"],
                "indexes": [
                    models.Index(
                        fields=["province", "zone_type"],
                        name="rsu_geograp_provinc_8a3e30_idx",
                    ),
                    models.Index(
                        fields=["accessibility_score"],
                        name="rsu_geograp_accessi_2b8f19_idx",
                    ),
                    models.Index(
                        fields=["priority_level"], name="rsu_geograp_priorit_f3f6d4_idx"
                    ),
                ],
                "unique_together": {("location_name", "province", "commune")},
            },
        ),
        migrations.AddIndex(
            model_name="personidentity",
            index=models.Index(fields=["rsu_id"], name="identity_ap_rsu_id_203e9d_idx"),
        ),
        migrations.AddIndex(
            model_name="personidentity",
            index=models.Index(fields=["nip"], name="identity_ap_nip_038e11_idx"),
        ),
        migrations.AddIndex(
            model_name="personidentity",
            index=models.Index(
                fields=["province", "verification_status"],
                name="identity_ap_provinc_1df5b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personidentity",
            index=models.Index(
                fields=["created_at"], name="identity_ap_created_41e6bd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="householdmember",
            unique_together={("household", "person")},
        ),
        migrations.AddIndex(
            model_name="rbppsync",
            index=models.Index(
                fields=["person", "sync_type"], name="rsu_rbpp_sy_person__38157d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rbppsync",
            index=models.Index(
                fields=["sync_status"], name="rsu_rbpp_sy_sync_st_f6b8bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rbppsync",
            index=models.Index(
                fields=["next_retry_at"], name="rsu_rbpp_sy_next_re_4a8198_idx"
            ),
        ),
    ]
