# Generated by Django 5.0.8 on 2025-09-26 03:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="personidentity",
            name="rsu_persons_provinc_b5c7b7_idx",
        ),
        migrations.RemoveIndex(
            model_name="personidentity",
            name="rsu_persons_verific_156322_idx",
        ),
        migrations.RemoveIndex(
            model_name="personidentity",
            name="rsu_persons_birth_d_a49faf_idx",
        ),
        migrations.RenameField(
            model_name="personidentity",
            old_name="rbpp_last_sync",
            new_name="rbpp_sync_date",
        ),
        migrations.RenameIndex(
            model_name="personidentity",
            new_name="identity_ap_rsu_id_203e9d_idx",
            old_name="rsu_persons_rsu_id_630a71_idx",
        ),
        migrations.RenameIndex(
            model_name="personidentity",
            new_name="identity_ap_nip_038e11_idx",
            old_name="rsu_persons_nip_3b7a6e_idx",
        ),
        migrations.RemoveField(
            model_name="personidentity",
            name="chronic_diseases",
        ),
        migrations.RemoveField(
            model_name="personidentity",
            name="employer",
        ),
        migrations.RemoveField(
            model_name="personidentity",
            name="last_survey_date",
        ),
        migrations.RemoveField(
            model_name="personidentity",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="personidentity",
            name="phone_number_alt",
        ),
        migrations.RemoveField(
            model_name="personidentity",
            name="rbpp_sync_errors",
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="commune",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="data_completeness_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Score complétude (%)",
            ),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "Aucune"),
                    ("INCOMPLETE_PRIMARY", "Primaire Incomplet"),
                    ("PRIMARY", "Primaire"),
                    ("SECONDARY", "Secondaire"),
                    ("HIGH_SCHOOL", "Baccalauréat"),
                    ("TECHNICAL", "Formation Technique"),
                    ("UNIVERSITY", "Universitaire"),
                    ("POSTGRADUATE", "Post-universitaire"),
                ],
                max_length=20,
                null=True,
                verbose_name="Niveau d'éducation",
            ),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Célibataire"),
                    ("MARRIED", "Marié(e)"),
                    ("DIVORCED", "Divorcé(e)"),
                    ("WIDOW", "Veuf/Veuve"),
                    ("COHABITING", "Concubinage"),
                    ("SEPARATED", "Séparé(e)"),
                ],
                default="SINGLE",
                max_length=15,
                verbose_name="Statut matrimonial",
            ),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format requis: +241XXXXXXXX pour Gabon",
                        regex="^\\+241[0-9]{8}$",
                    )
                ],
                verbose_name="Téléphone principal",
            ),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTUAIRE", "Estuaire"),
                    ("HAUT_OGOOUE", "Haut-Ogooué"),
                    ("MOYEN_OGOOUE", "Moyen-Ogooué"),
                    ("NGOUNIE", "Ngounié"),
                    ("NYANGA", "Nyanga"),
                    ("OGOOUE_IVINDO", "Ogooué-Ivindo"),
                    ("OGOOUE_LOLO", "Ogooué-Lolo"),
                    ("OGOOUE_MARITIME", "Ogooué-Maritime"),
                    ("WOLEU_NTEM", "Woleu-Ntem"),
                ],
                max_length=20,
                null=True,
                verbose_name="Province",
            ),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En Attente"),
                    ("VERIFIED", "Vérifié"),
                    ("REJECTED", "Rejeté"),
                    ("REQUIRES_REVIEW", "Nécessite Révision"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut vérification",
            ),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date vérification"
            ),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_persons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifié par",
            ),
        ),
        migrations.AddIndex(
            model_name="personidentity",
            index=models.Index(
                fields=["province", "verification_status"],
                name="identity_ap_provinc_1df5b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personidentity",
            index=models.Index(
                fields=["created_at"], name="identity_ap_created_41e6bd_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="personidentity",
            table=None,
        ),
    ]
