# Generated by Django 5.0.8 on 2025-09-26 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity_app", "0003_update_geographic_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="geographicdata",
            name="geo_province_district_idx",
        ),
        migrations.RenameIndex(
            model_name="geographicdata",
            new_name="rsu_geograp_accessi_2b8f19_idx",
            old_name="geo_accessibility_idx",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="area_km2",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="center_latitude",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="center_longitude",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="department",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="difficult_access_rainy_season",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="distance_to_admin_center_km",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="distance_to_bank_km",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="distance_to_health_center_km",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="distance_to_hospital_km",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="distance_to_main_road_km",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="distance_to_market_km",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="distance_to_school_km",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="distance_to_secondary_school_km",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="flood_risk",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="internet_available",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="mobile_network_coverage",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="population_estimate",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="public_transport_available",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="road_condition",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="security_concerns",
        ),
        migrations.RemoveField(
            model_name="geographicdata",
            name="service_availability_score",
        ),
        migrations.AddField(
            model_name="geographicdata",
            name="distance_to_market",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Distance marché (km)"
            ),
        ),
        migrations.AddField(
            model_name="geographicdata",
            name="distance_to_road",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Distance route praticable (km)"
            ),
        ),
        migrations.AddField(
            model_name="geographicdata",
            name="estimated_population",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Population estimée"
            ),
        ),
        migrations.AddField(
            model_name="geographicdata",
            name="has_internet",
            field=models.BooleanField(default=False, verbose_name="Accès internet"),
        ),
        migrations.AddField(
            model_name="geographicdata",
            name="has_mobile_coverage",
            field=models.BooleanField(default=False, verbose_name="Couverture mobile"),
        ),
        migrations.AddField(
            model_name="geographicdata",
            name="population_density",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VERY_LOW", "Très Faible"),
                    ("LOW", "Faible"),
                    ("MEDIUM", "Moyenne"),
                    ("HIGH", "Élevée"),
                    ("VERY_HIGH", "Très Élevée"),
                ],
                max_length=20,
                null=True,
                verbose_name="Densité population",
            ),
        ),
        migrations.AddField(
            model_name="geographicdata",
            name="priority_level",
            field=models.CharField(
                choices=[
                    ("LOW", "Faible"),
                    ("MEDIUM", "Moyenne"),
                    ("HIGH", "Élevée"),
                    ("CRITICAL", "Critique"),
                ],
                default="MEDIUM",
                max_length=20,
                verbose_name="Niveau priorité",
            ),
        ),
        migrations.AddField(
            model_name="geographicdata",
            name="vulnerability_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Score vulnérabilité (0-100)",
            ),
        ),
        migrations.AlterField(
            model_name="geographicdata",
            name="commune",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Commune"
            ),
        ),
        migrations.AlterField(
            model_name="geographicdata",
            name="location_name",
            field=models.CharField(max_length=200, verbose_name="Nom localité"),
        ),
        migrations.AlterField(
            model_name="geographicdata",
            name="province",
            field=models.CharField(
                choices=[
                    ("ESTUAIRE", "Estuaire"),
                    ("HAUT_OGOOUE", "Haut-Ogooué"),
                    ("MOYEN_OGOOUE", "Moyen-Ogooué"),
                    ("NGOUNIE", "Ngounié"),
                    ("NYANGA", "Nyanga"),
                    ("OGOOUE_IVINDO", "Ogooué-Ivindo"),
                    ("OGOOUE_LOLO", "Ogooué-Lolo"),
                    ("OGOOUE_MARITIME", "Ogooué-Maritime"),
                    ("WOLEU_NTEM", "Woleu-Ntem"),
                ],
                max_length=50,
                verbose_name="Province",
            ),
        ),
        migrations.AlterField(
            model_name="geographicdata",
            name="zone_type",
            field=models.CharField(
                choices=[
                    ("URBAN_CENTER", "Centre Urbain"),
                    ("URBAN_PERIPHERY", "Périphérie Urbaine"),
                    ("RURAL_ACCESSIBLE", "Rural Accessible"),
                    ("RURAL_REMOTE", "Rural Isolé"),
                    ("COASTAL", "Zone Côtière"),
                    ("FOREST", "Zone Forestière"),
                    ("MINING", "Zone Minière"),
                    ("BORDER", "Zone Frontalière"),
                ],
                default="RURAL_ACCESSIBLE",
                max_length=30,
                verbose_name="Type de zone",
            ),
        ),
        migrations.AddIndex(
            model_name="geographicdata",
            index=models.Index(
                fields=["province", "zone_type"], name="rsu_geograp_provinc_8a3e30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geographicdata",
            index=models.Index(
                fields=["priority_level"], name="rsu_geograp_priorit_f3f6d4_idx"
            ),
        ),
    ]
