# Generated by Django 5.0.8 on 2025-09-26 21:13

import apps.identity_app.models.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity_app", "0005_add_test_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personidentity",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Format: +241XXXXXXXX ou 0XXXXXXXX",
                max_length=20,
                null=True,
                validators=[apps.identity_app.models.person.validate_gabonese_phone],
                verbose_name="Numéro de Téléphone",
            ),
        ),
    ]
