# Generated by Django 5.0.8 on 2025-09-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity_app", "0006_fix_household_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="personidentity",
            name="nationality",
            field=models.CharField(
                choices=[
                    ("GABONAISE", "Gabonaise"),
                    ("AUTRE_CEMAC", "Autre CEMAC"),
                    ("AUTRE_AFRIQUE", "Autre Afrique"),
                    ("AUTRE", "Autre"),
                ],
                default="GABONAISE",
                max_length=50,
                verbose_name="Nationalité",
            ),
        ),
    ]
