# Generated by Django 5.0.8 on 2025-10-05 23:33

import apps.identity_app.models.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity_app", "0015_fix_employment_index"),
    ]

    operations = [
       
        migrations.AlterField(
            model_name="personidentity",
            name="employer",
            field=models.CharField(
                blank=True,
                help_text="Nom de l'entreprise/organisation employeur",
                max_length=200,
                null=True,
                verbose_name="Employeur",
            ),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMPLOYED_FORMAL", "Employé Formel (CDI/CDD)"),
                    ("EMPLOYED_INFORMAL", "Employé Informel"),
                    ("SELF_EMPLOYED", "Travailleur Indépendant"),
                    ("UNEMPLOYED", "Sans Emploi"),
                    ("STUDENT", "Étudiant"),
                    ("RETIRED", "Retraité"),
                    ("HOMEMAKER", "Au Foyer"),
                    ("UNABLE_TO_WORK", "Inapte au Travail"),
                ],
                help_text="Situation professionnelle actuelle",
                max_length=20,
                null=True,
                verbose_name="Statut d'Emploi",
            ),
        ),
        migrations.AlterField(
            model_name="personidentity",
            name="phone_number_alt",
            field=models.CharField(
                blank=True,
                help_text="Numéro secondaire (optionnel)",
                max_length=20,
                null=True,
                validators=[apps.identity_app.models.person.validate_gabonese_phone],
                verbose_name="Téléphone Alternatif",
            ),
        ),
    ]
